spring:
  application:
    name: "Homework #11"

  data:
    mongodb:
      host: localhost
      port: 27017
      database: awesomeMongo


mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.hw.changelogs
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    com.github.cloudyrock.mongock: debug
    root: info


