spring:
  main:
    allow-circular-references: true

  application:
    name: "Homework #14"

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true
    noninteractive:
        enabled: false
    command:
      version:
        enabled: false

#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver

  data:
    mongodb:
      host: localhost
      port: 27017
      database: awesomeMongo

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

