spring:
  application:
    name: "Homework #5"
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  h2:
    console:
      enabled: true

